version: '3'

services:
  keycloak_db:
    container_name: keycloak_db
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: '********'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:15.0.2
    command: -c standalone.xml
    environment:
      JAVA_OPTS_APPEND: "-Xmx1G"
      DB_VENDOR: postgres
      DB_ADDR: keycloak_db
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: '********'
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: '********'
      KEYCLOAK_FRONTEND_URL: 'https://keycloak.siguv.de/auth/'
      PROXY_ADDRESS_FORWARDING: 'true'
      # HTTP_PROXY: http://10.33.176.21:3128
      # HTTPS_PROXY: http://10.33.176.21:3128
    ports:
      - '8080:8080'
      - '8443:8443'
    volumes:
      - ./startup-scripts:/opt/jboss/startup-scripts
      - ./providers:/opt/jboss/keycloak/standalone/deployments
    depends_on:
      - keycloak_db
    restart: always
