GET http://localhost:8081/users
Accept: application/json

###

GET http://localhost:8081/users/count
Accept: application/json

###

GET http://localhost:8081/users/55746c21-af2e-491d-9af4-6d7d46ede50b
Accept: application/json

###

POST http://localhost:8081/credentials
Content-Type: application/json

{
  "userId": "55746c21-af2e-491d-9af4-6d7d46ede50b",
  "value": "3858f62230ac3c915f300c664312c63f",
  "type": "password"
}

###

PUT http://localhost:8081/credentials
Content-Type: application/json

{
  "userId": "55746c21-af2e-491d-9af4-6d7d46ede50b",
  "value": "3858f62230ac3c915f300c664312c63f",
  "type": "password"
}

###
