version: '3.9'

services:
  api:
    container_name: api_mock
    image: muonsoft/openapi-mock:latest
    environment:
      OPENAPI_MOCK_SPECIFICATION_URL: /tmp/virtualUserStorage.yaml
      OPENAPI_MOCK_USE_EXAMPLES: if_present
    volumes:
      - ../api/virtualUserStorage.yaml:/tmp/virtualUserStorage.yaml
    ports:
      - '8081:8080'

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:15.0.2
    command: -c standalone.xml --debug *:8787
    environment:
      DB_VENDOR: h2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /opt/jboss/novareto-realm.json
    ports:
      - '8080:8080'
      - '8787:8787'
    volumes:
      - ./target/virtual-user-spi-1.0-SNAPSHOT.jar:/opt/jboss/keycloak/standalone/deployments/virtual-user-spi.jar
      - ./src/test/resources/novareto-realm.json:/opt/jboss/novareto-realm.json
      - ./config:/opt/jboss/startup-scripts
