name: CI build for VirtualUser Provider

on:
  push:
    paths:
      - virtual-user-spi/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out sources
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Maven build
        run: mvn -B package
        working-directory: virtual-user-spi
      - name: Copy artifacts
        run: mkdir staging && cp target/*.jar staging
        working-directory: virtual-user-spi
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: virtual-user-spi/staging
